
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fr.ul.miashs.compil.parsing;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int READ = 10;
  public static final int LT = 17;
  public static final int ELSE = 7;
  public static final int PLUS = 11;
  public static final int RBRACE = 25;
  public static final int RPAREN = 23;
  public static final int INT = 4;
  public static final int WHILE = 8;
  public static final int IDENTIFIER = 28;
  public static final int RETURN = 5;
  public static final int FUNCTION = 2;
  public static final int IF = 6;
  public static final int LBRACE = 24;
  public static final int LPAREN = 22;
  public static final int GT = 16;
  public static final int LE = 18;
  public static final int WRITE = 9;
  public static final int COMMA = 26;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int MULT = 13;
  public static final int DIV = 14;
  public static final int GE = 19;
  public static final int MINUS = 12;
  public static final int error = 1;
  public static final int EQ = 20;
  public static final int ASSIGN = 15;
  public static final int NEQ = 21;
  public static final int VOID = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "VOID",
  "INT",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "WRITE",
  "READ",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "ASSIGN",
  "GT",
  "LT",
  "LE",
  "GE",
  "EQ",
  "NEQ",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "NUMBER",
  "IDENTIFIER"
  };
}

